### ISSUE TITLE
Use RBAC to customize VM details page

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1067]
Per @jonnyfiveiq (edited for "public" viewing):

> I was to customise what the users see in the property pages, in case someone doesn't want all items showing. This should be controlled through RBAC, or some sort of template. where by the admin can decide what is shown on a per group, role or user basis.

@serenamarie125 @Loicavenel my quick thought for this would be to have a card similar to the no data available card, but say you are not authorized.  Admittedly it's not a great user experience, but it would be a good stop gap measurement.  Thoughts?

**Comment by jonnyfiveiq** [comment]
UX would be same as today? Simply extend the tree view in the RBAC area to accommodate a new leaf that is SUI VM Property Page, and allow the user to turn on or off sections of the property page. That that would be the minimum.

Really we need to be able to control each individual item on the page, this would be too much for the RBAC tree control and why I proposed using more of a template approach. Where you save a template of how you want it to look, and attach that to RBAC roles, groups or users. Then you can copy it to other roles etc...

**Comment by Loicavenel** [comment]
@chriskacerguis in the RBAC we will have to details the different Cards we have but, we have to thinks about what it is going to looks like.. @serenamarie125 do you see any nice option here?

**Comment by serenamarie125** [comment]
@chriskacerguis I don't think would be a good experience

@jonnyfiveiq would it be easy for us to identify sections?  For examples
1 - Row 1 with the generic VM Details
2 - Row 2 with the Timeline View
3 - Row 3 with Utilization, Disk Usage & Disk I/O
4  - Row 4 Tags, Custom Attributes & Smart State

If we did it that way, we could still ensure that what's viewed will look decent because it will be full rows.  If the above sections make sense, I think we may still be able to use the RBAC tree control.  When the editable dashboards come to fruition, it will be much easier, as each widget should probably have RBAC control.

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1502790
