### ISSUE TITLE
Remove dollar (chargebacks) on the “My Services” list

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1148]
Remove dollar (chargebacks) on the “My Services” list

**Comment by ohadlevy** [comment]
Prior to implementing this issue, I would double check how much faster is loading the API without this info, and consider either to do two api calls (fast with less data but enough to render the page, and second with more data while showing loading state/spinner on those specific elements). /cc @serenamarie125 @Loicavenel

**Comment by Loicavenel** [comment]
@chriskacerguis @ohadlevy if we remove $, we are removing a functionality here.. the number of $ is indicating of low, medium and high cost

**Comment by AllenBW** [comment]
So if removing the attribute has no tangible impact on load times, would we still want to remove it?

**Comment by AllenBW** [comment]
OK so  I was talking to @imtayadeway who was saying that this attribute alone likely is not the cause of the load times... 

@chriskacerguis @ohadlevy do we still want to pull it?

**Comment by chriskacerguis** [comment]
@Loicavenel question...does it make sense to have the relative cost (the $) on the My Services page?  It seems that it would make more sense on the Catalog page, as once the buy the service, do they really care what it costs?  

That aside, we are just looking to speed things up until the API team can complete its work.

**Comment by serenamarie125** [comment]
I'm confused as to why we are revisiting these designs.  This relative cost design was done, reviewed with customers and PM a long time ago.  Here is the design: https://manageiq.github.io/manageiq-design/UX/ui-service/MyServices/design#list-view

The use case was to allow the user to show the costs of their services, not what's in the catalog, that's why it's shown in My Services.

**Comment by ohadlevy** [comment]
@serenamarie125 thanks for your feedback, the main context of this issue is performance, within that context, @chriskacerguis and I were looking to what can speed up the performance - and we assumed that fetching the cost metrics are "expensive" - however from the thread it seems that's not case. I would suggest to keep investigating what are the "low hanging fruits" that can improve performance and try to balance it with UXD.
