### ISSUE TITLE
Remove numbers from sidebar

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1150]
Remove numbers from sidebar and the polling as well (for speed)

**Comment by ohadlevy** [comment]
@Loicavenel does showing the number of services, orders etc in the vertical nav bar is useful? it seems like we have a background API call that keeps updating those numbers, but I would assume 10+ icon or similar would probably be enough, as users don't usually care if its a large number anyway?

**Comment by AllenBW** [comment]
It would cut down on polling a yuge amount <3

**Comment by Loicavenel** [comment]
I think it is useful, you know how many service you have.. Do you want to show it only in the Dashboard? and not in Nav Bar? When you load the Dashboard you have to get it anyway???

@serenamarie125 your thought?

**Comment by chriskacerguis** [comment]
@Loicavenel So, just some background:

1. Those are two different calls
2. We load the nav bar and make 3 calls (one for each "section").  

I can see the benefit of polling for the # of services, but does it matter how many orders you have placed (that you need to see it on the side bar)?  Same thing with the # of catalog items?

That said, regarding the Dashboard.  I haven't seen any mocks, but I know that is something that is going to get redone at some point, so even though we are calling the same data for it and the sidebar now, we might not be in the future.

**Comment by serenamarie125** [comment]
@ohadlevy When we designed the SUI initially, it was an intentional decision to have the "badges" included in the vertical navigation.

@Loicavenel I definitely see value to this ... the user is able to see the My Services number increment or decrement when services are approved/provisioned and/or retired, regardless of where they are in the UI

Why do you have to continue to poll?  Can you just updated the badge when a service is provisioned or retired?

@chriskacerguis what kind of dashboard mocks are you looking for?  Have you requested something new?  The last request was fulfilled with this documentation (note these are low fidelity mocks): https://manageiq.github.io/manageiq-design/UX/ui-service/Dashboard/design

**Comment by chriskacerguis** [comment]
@serenamarie125 

> Can you just updated the badge when a service is provisioned or retired?
That's why we have to poll, so we can update the count.  We don't have a push mechanism that would do that (backend team would need to add it)

> what kind of dashboard mocks are you looking for?
I'm not looking for anything, and I haven't requested anything new.  I though at some point the dashboards were getting overhauled (I remember talking about that at the start of the release, but priorities changed?)

**Comment by chriskacerguis** [comment]
All that said, the polling API calls are minimal, so removing this won't do anything for performance.

**Comment by serenamarie125** [comment]
@chriskacerguis as far as the dashboards, the editable dashboard effort is a phased effort.  I haven't heard of it affecting SUI in 4.6, but @Loicavenel can correct me here.

**Comment by chriskacerguis** [comment]
@serenamarie125 it was VERY briefly talked about that we would "share" the component.  That's all I heard...and haven't heard anything else.  Might have just been early planning.  /shrug no big deal
