### ISSUE TITLE
Rename "Self Service UI" to just "Service UI"

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#147]
As the role of the SSUI has expanded, we need to rename the Self Service UI to the "Service UI"

**Comment by chriskacerguis** [comment]
@AllenBW have you updated all the references in the code / docs to be "Service UI" (instead of "Self Service UI")?

**Comment by AllenBW** [comment]
@chriskacerguis There remains work to be done on this:
* serve url should be `http://localhost:3001/service/` rather than `http://localhost:3001/self_service/` 
* repo and root folder should be `service` (and readme update to this affect)
* app title still mentions self-service (and a few other places in app need to be updated)

**Comment by serenamarie125** [comment]
@chriskacerguis @AllenBW this is for post 4.2, correct ?   I'm assuming so, since 4.2 will remain solely self service.

**Comment by chriskacerguis** [comment]
This is for the F release.

**Comment by AllenBW** [comment]
eeeeeeeyoooooo @chriskacerguis so hold off on this for a bit?

**Comment by AllenBW** [comment]
@chriskacerguis 

We can also close this one now, referenced but didn't close in pr #254
