### ISSUE TITLE
Direct link to service redirects to login page even if user authorized

### ISSUE THREAD

**Issue by bekasovoleg** [ManageIQ/manageiq-ui-service#1527]
Description of problem:
Direct link to service redirects to login page even if user is authorized

How reproducible:

Steps to Reproduce:
1. Login to UI Service
2. Open new tab and go to ui/serivce/services/:id. We get login page instead of specified service page.

Actual results:
We get login page instead of specified service page.

Expected results:
Page with specified service (ui/serivce/services/:id).

Additional info:

**Comment by bekasovoleg** [comment]
@chalettu looks like problem in code below
https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/app/core/authorization.config.js#L66
`console.log(RBAC.all())` returns empty object

**Comment by bekasovoleg** [comment]
@AllenBW, take a look pls

**Comment by himdel** [comment]
Definitely a bug, if you can open a PR, I'll merge :)

**Comment by himdel** [comment]
When logged in as admin with valid credentials...

going to / .. should load the dashboard (at the same url), but goes to /login instead
going to /services/80 .. should load the url, redirects to /login

(opening the url in the same tab seems to work, just not different tabs, probably caused by the use of sessionStorage as opposed to localStorage)

Looking into it.

**Comment by himdel** [comment]
Originally implemented in https://github.com/ManageIQ/manageiq/pull/5904 (although back then, sessionStorage was shared between tabs)

**Comment by bekasovoleg** [comment]
@himdel good job, thanks a lot!
