### ISSUE TITLE
Require parameter "Name" for snapshots

### ISSUE THREAD

**Issue by ahrechushkin** [ManageIQ/manageiq-ui-service#1567]
https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/app/services/process-snapshots-modal/process-snapshots-modal.html#L9
Why name is required?
In RHV and Ovirt required field is Description

**Comment by himdel** [comment]
So,
there is no mismatch with the fields themselves,

both SUI and Ops UI use the same 3 fields:

name - Name
memory - Memory
description - Description


The difference is that for SUI:

* name is always shown and required
* description is never required

But for Ops UI:

* when `@record.snapshot_name_optional?`
  * name is hidden, not required
  * description is required
* otherwise, when `@record.vendor == 'openstack'`
  * name is shown & required
  * description is required
* otherwise
  * name is shown & required
  * description is optional

The `@record.vendor == 'openstack'` is probably clear,
`snapshot_name_optional?` seems to be implemented for ovirt only, hardcoded to `true` (and not accessible via the API).

**Comment by himdel** [comment]
@h-kataria I assume we should copy the whole UI logic?

(I can work around `snapshot_name_optional?` being unavailable by checking `@record.vendor` in both cases.)

**Comment by h-kataria** [comment]
@himdel i agree it should work the same way as in OPS UI.
