### ISSUE TITLE
Branding above left navigation is smaller than that of normal UI

### ISSUE THREAD

**Issue by john-dupuy** [ManageIQ/manageiq-ui-service#1638]
Description of problem:
This is similar to the issue being fixed in https://github.com/ManageIQ/manageiq-ui-service/pull/1637, but here the issue is in the left navigation after the user has logged in. 

How reproducible:
100%

Steps to Reproduce:
1. Login to SSUI
2. Look at branding above the left nav

Actual results:
It looks small compared to normal UI:
![Screenshot from 2020-04-15 10-12-16](https://user-images.githubusercontent.com/44065123/79349420-2f658300-7f04-11ea-995b-0d1830ba0255.png)

Expected results:
Size should match the normal UI:
![Screenshot from 2020-04-15 10-11-46](https://user-images.githubusercontent.com/44065123/79349461-3d1b0880-7f04-11ea-8123-32fa88d54a2a.png)

Additional info:
cc @himdel

**Comment by himdel** [comment]
ui-service is using the patternfly default styling for `.navbar-pf-vertical .navbar-brand .navbar-brand-icon` from `_navbar_vertical.scss`,
ui-classic is setting this in `vendor/assets/brand.scss` - but to 20px as well

Looks like different paddings/margins, :eyes:

**Comment by himdel** [comment]
So this is not an upstream issue..

ui-classic:
![classic](https://user-images.githubusercontent.com/289743/79458146-f4854d00-7fe0-11ea-8cfd-6d8f9e643315.png)

ui-service:
![service](https://user-images.githubusercontent.com/289743/79458173-f9e29780-7fe0-11ea-8b23-5770bfddbe20.png)

(There is a slight spacing difference because of the SUI loading bar, but no real difference in size.)
