### ISSUE TITLE
Security upgrade required for lodash/angular/bootstrap-select

### ISSUE THREAD

**Issue by bhadrim** [ManageIQ/manageiq-ui-service#1672]
@Fryguy @himdel Based on the new webpack manifest for service, I analyzed the output the following packages are affected by security issue. I believe they are all valid issues and we are looking for fix on master and Jansa (N and N-1). Thank you.

Module: bootstrap-select
Issue: See https://nvd.nist.gov/vuln/detail/CVE-2020-8203
Versions affected: https://www.npmjs.com/advisories/1522/versions
Version used: 1.12.2 (jansa and master)
Sev: Medium

Module: lodash
Issue: See https://nvd.nist.gov/vuln/detail/CVE-2020-8203
Versions affected: <= 4.17.15
Version used: 4.17.11 (jansa and master)
Sev: High

Module: angular
Issue: See https://github.com/advisories/GHSA-89mq-4x47-5v83
Versions affected: < 1.7.9
Version used: 1.7.5 (jansa and master)
Sev: High

Module: angular
Issue: See https://github.com/advisories/GHSA-mhp6-pxh8-r675
Versions affected: < 1.8.0 (jansa and master)
Version used: 1.7.5
Sev: Low

**Comment by himdel** [comment]
lodash can be fixed by `yarn upgrade`,
`bootstrap-select` can't be fixed without updating patternfly (but I can add overrides to use @pf3/select instead, similar to what ui-classic does, and fix it there)
`angular` 1.7 can be fixed by updating package.json (to use 1.7.9) and upgrading,
`angular` 1.8  will likely be problematic similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/6452, angular-patternfly still depends on angular 1.5

**Comment by himdel** [comment]
Fixed in https://github.com/ManageIQ/manageiq-ui-service/pull/1674,
it's a large change, but only really touches tooling, specs and dependencies, so should be safe to backport.

**Comment by bhadrim** [comment]
@himdel Thank you for all your work and quick turnaround time.

**Comment by himdel** [comment]
No problem :) That should also make the ui-classic angular upgrade a bit easier to tackle.
