### ISSUE TITLE
Jansa2 Webmks MIME error

### ISSUE THREAD

**Issue by dimitar1128** [ManageIQ/manageiq-ui-service#1688]
It's giving error when accessing vm that is provisioned in self_service.

Steps to Reproduce:
1. Access /self_service with the user account who provisioned the vm.
2. Click the provisioned vm from "My Services" and try to access by clicking "VM HTML5 Console" button from "Access" dropdown.

Actual results:
It should access the vm.

Expected results:
It's giving MIME error. See attached image.
![Capture](https://user-images.githubusercontent.com/62528203/99801770-3cec8680-2b3f-11eb-9aeb-372a98594e1e.PNG)

https://192.168.2.158/styles/console_webmks-0f63f536614c2020cf54.css
Result: See attached image.
![Capture1](https://user-images.githubusercontent.com/62528203/99801880-65748080-2b3f-11eb-8c50-e13ab173fa12.PNG)

Additional info:

**Comment by himdel** [comment]
`/self_service` is something that went away in euwe, in favor of `/ui/service` .. so there's a chance you're running an ancient version, @dimitar1128 can you share more information about your environment please?

If that's not the issue, as per https://www.manageiq.org/docs/guides/remote_consoles, WebMKS consoles are not supported out of the box, you need to download the files yourself .. so this could also be caused by those files not being there, it seems the request for the JS file fails with a 404, the request for the css fails with a html version of the same.

**Comment by himdel** [comment]
The provider & version the VM is based on could also be useful, as well as the exact version of SUI.

**Comment by himdel** [comment]
Using current jansa, `yarn run build` does produce a `manageiq/public/ui/service/console.webmks.html` with a reference to `../styles/console_webmks-7e5270e13a4e02138d36.css` and `../js/console_webmks-7e5270e13a4e02138d36.js`, as well as those files.

So you may want to check there, whether the problem is that the hash in the html does not match the files that actually exist, or if the files don't exist at all.

**Comment by himdel** [comment]
Oh, the URL is

> https://192.168.2.158/styles/console_webmks-0f63f536614c2020cf54.css

which means this is definitely a custom build. So I suggest checking any customizations, `config/webpack.dev.js` defines how the `console_webmks` entrypoint is build, and configures `HtmlWebpackPlugin` to generate the console html accordingly.

**Comment by dimitar1128** [comment]
Well, I have not customized anything

**Comment by himdel** [comment]
@dimitar1128 Is this an unofficial docker image then? A development environment?

**Comment by dimitar1128** [comment]
nope, the version is jansa2 and I got the image from the manageiq page

**Comment by himdel** [comment]
Just to prevent misundestandings, can you share the URL of the image please? I'll try running it to reproduce

**Comment by dimitar1128** [comment]
@himdel here is the url of the image.
http://releases.manageiq.org/manageiq-vsphere-jansa-2.ova

**Comment by himdel** [comment]
Reproducer:

1. run a jansa-2 appliance
2. open `/ui/service/console/webmks.html`
3. see browser console

Actual:

Refused to apply style from 'https://localhost/styles/console_webmks-0f63f536614c2020cf54.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
console_webmks-0f63f536614c2020cf54.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Expected:

no errors, the files should load from **/ui/service**/styles..

---

```html
<base href="/">
<link href="../styles/console_webmks-0f63f536614c2020cf54.css" rel="stylesheet">
...
<script src="../js/console_webmks-0f63f536614c2020cf54.js">
```

So, the relative URLs in code are right, but the base href definitiely isn't.
