### ISSUE TITLE
Jansa3 Webmks - can't open VM HTML5 Console in UI Service -  

### ISSUE THREAD

**Issue by sebrower** [ManageIQ/manageiq-ui-service#1697]
Description of problem:
The VM HTML Console doesn't work in UI service on jansa-3. 

How reproducible:
Always

Steps to Reproduce:
1. Log in URL ui/service
2. Click the provisioned vm from "My Services" and try to access by clicking "VM HTML5 Console" button from "Access" dropdown.
3. In browser (firefox), Open Menu -> Web Developer -> Toggle tools

Actual results:
The console doesn't appear. And in the Toggle tools, we can see this message:
Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack:///js/console_webmks-f0c60a87506a5c3f1ef4.js
![image](https://user-images.githubusercontent.com/21200860/107029694-bd6e6b00-67af-11eb-8ae9-ef45a6600150.png)

But when I'm connecting in admin portal under services -> My services, select my VM -> access and click on VM console, the console appears whitout problem.

Expected results:
The HTML Console must appear like in the admin portal.

Others informations
VMs are in ESX plateform.

**Comment by himdel** [comment]
Ah, yes, that's a known bug, fixed in https://github.com/ManageIQ/manageiq-ui-service/pull/1681

I'll prepare a fix-only PR for jansa

**Comment by himdel** [comment]
The fix was backported to jansa on [Dec 7, 2020](https://github.com/ManageIQ/manageiq-ui-service/pull/1690#issuecomment-747724302), any builds later than that should have the fix :).

@sebrowser can you confirm this is fixed on jansa-3 please?

**Comment by sebrower** [comment]
Hi @himdel ,

It was a mistake in my title. The issue is on Jansa-3.
On jansa-3, the problem described in #1690 is resolved but is not enough to have the console.  
I confirm you that the issue is for Jansa-3.

**Comment by himdel** [comment]
Ah, any chance you could expose a failing appliance somewhere I can access it please? I'm afraid I have no way of testing webmks...

If not, I'm going to need a bit more info, could you also try this in chrome please? Not because I'm expecting it to work, but because I'm hoping to recognize the error message, and maybe see a backtrace.

It's either attempting to do HTTP requests for a webpack:// url, and failing because that doesn't make sense,
or something being fetched by the script on that URL is failing, but then I need to know what it's trying to fetch and how the response looks.

What it *should* be doing is fetch a `/webmks/wmks.min.js` file (absolute path, outside `/ui/service` because that's served from `manageiq/public/webmks/`). Can you tell if that's the URL it's trying to access? And, does accessing it manually yield a javascript response?

**Comment by sebrower** [comment]
Hi @himdel ,

I can't give you access on our plateform.

I'm prepared to help you to resolve this.
I have open in Chrome and I have seen some other things. I have this following errors in console:
console_webmks-f0c60a87506a5c3f1ef4.js:621 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (console_webmks-f0c60a87506a5c3f1ef4.js:621)
    at Module.432 (console_webmks-f0c60a87506a5c3f1ef4.js:621)
    at i (console_webmks-f0c60a87506a5c3f1ef4.js:1)
    at Object.429 (console_webmks-f0c60a87506a5c3f1ef4.js:621)
    at i (console_webmks-f0c60a87506a5c3f1ef4.js:1)
    at console_webmks-f0c60a87506a5c3f1ef4.js:1
    at console_webmks-f0c60a87506a5c3f1ef4.js:1
 I have alse the error : **Could not load content for webpack:///js/console_webmks-f0c60a87506a5c3f1ef4.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME**)
I send you the javascript in attachment.
[console_webmks-f0c60a87506a5c3f1ef4.txt](https://github.com/ManageIQ/manageiq-ui-service/files/5952751/console_webmks-f0c60a87506a5c3f1ef4.txt)

The file /webmks/wmks.min.js is present as recommended for manageiq. 
I can't see if the error comes from the call to this file. I see only the error on the script where there is a reference to this file.

**Comment by himdel** [comment]
OK, I *think* this means that `console_webmks.js` itself (so, our code, or something required by that file) is failing *during* require, leading to the surprising error of failing while including a backtrace from it.

Given that `Cannot assign to read only property 'exports'`, it looks like a library using an amd/ujs/cjs compatibility shim is failing to detect the right way to export.

Which is surprising because ui-service itself is using the same requires the same way.

... OK, I think I've found it .. `client/console/common.js` is only included in consoles, does `import... from...`, but also does `module.exports = ...`, that's definitely not a valid combination.
