### ISSUE TITLE
Opening the service ui results in downloading app.js over and over

### ISSUE THREAD

**Issue by JohannesUebleis** [ManageIQ/manageiq-ui-service#1864]
Description of problem:

Service ui downloads the app.js eg. /js/app-82a331394b32444f2703.js over and over. More often, the more Services a user has. In our case it even hindered the appliance unusable since opening the service ui resulted in over 1 GB of transferred data and overloading the appliance. Also you are not able to click on services anymore in the UI, since it starts reloading the app.js again.

How reproducible:

Every time you open/reload the page. 

Steps to Reproduce:
1. Open the service ui https://yourappliance/ui/service/
2.
3.

Actual results:

On the latest container version it downloads the app.js about 8 times -> around 40MB of total transferred data on loading the page.
Even more, the more services a user has requested.

Expected results:

On Oparin version the app.js only gets transferred once. -> around 6MB of total transferred data on loading the page.

Additional info:
I upgraded the appliance from Oparin to Petrosian, then i noticed i cant use the Service UI anymore.
I then tested the latest available container with Firefox, Chrome and Edge to see same results. Though Firefox was able to cache the app.js.

**Comment by DavidResende0** [comment]
@Fryguy, @agrare, So the issue seems to only pop up in production but I was able to recreate it on an appliance.
![image](https://github.com/ManageIQ/manageiq-ui-service/assets/64800041/0d22de36-d0eb-4dde-a7f1-4f2ea8606745)
![image](https://github.com/ManageIQ/manageiq-ui-service/assets/64800041/fc8deeb3-f27d-47f4-95ff-62b26e3cf866)

Like @JohannesUebleis mentioned it seems like firefox is smart enough to cache app.js but the issue still appears
![image](https://github.com/ManageIQ/manageiq-ui-service/assets/64800041/f7b4b835-6629-4b35-b0f3-565384594741)

**Comment by DavidResende0** [comment]
@JohannesUebleis this issue was accidentally introduced in a previous fix. https://github.com/ManageIQ/manageiq-ui-service/pull/1865 reverts the change while also fixing the original issue.
