### ISSUE TITLE
Migrate bower + npm to only npm for dependency management

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-ui-service#251]
No reason to have both of these dependency managers around, especially given #245 we stand to gain much from using npm.

This task is broken up into two parts:
- [ ] Transfer bower dependencies to package.json
- [ ] Ensure necessary dependencies are injected into dependency partials (gulp task)

**Comment by chriskacerguis** [comment]
cc @chalettu @dclarizio @martinpovolny @himdel @AparnaKarve

**Comment by AllenBW** [comment]
So it seems there are a few ways to skin this 😸 .  One is to use yarn, (`yarn install` instead of npm install and bower install) but there are a few issues [presently](https://bower.io/blog/2016/using-bower-with-yarn/).  Another is to completely rip out bower and use a combination of commonjs `require` and webpack/bowerserify to include the bundled assets in index.esj (leaning webpack)

If/when we move to angular 2, some key dependencies are published on npm but not bower (mainly https://ui-router.github.io/ng2/) .  

I am mildly concerned  that the trend of dependencies not being published on bower will cause trouble down the road. 🙈

**Comment by chriskacerguis** [comment]
I agree bower is dying. What is your recommendation for how to proceed?

**Comment by chalettu** [comment]
We can sit down and look at all our current dependencies, see if they are in npm.   We can then look into integrating webpack and the combo above.

**Comment by AllenBW** [comment]
They are, already checked 🤘🎷🐯

**Comment by martinpovolny** [comment]
I wonder if the priority is to get it done here or in the operations UI or both? @himdel?

I started putting together list of tasks related to splitting the various UIs here: https://www.pivotaltracker.com/n/projects/1619601 and the npm migration is among those.

**Comment by himdel** [comment]
Agreed, we should migrate both, rather soon ideally.  (In fact, I've already started looking into migrating manageiq, and there, we're missing a few dependencies.. `angular-patternfly-sass`, `jquery-1.8`, `jquery.observe_field`, `kubernetes-topology-graph`, `manageiq-ui-components`, `patternfly-timeline`, `spice-html5-bower`, `xml_display` - but I can fix that a bunch of those on Monday,)

As for `yarn`, on one hand it's very new, on the other, it does look good, is faster both when installing from scratch *and* when doing nothing, and since it uses the same `node_modules` and `package.json` and so can effectively be replaced by `npm` any time, I'd say what the hell, too tempting not to try :). I wonder if we'll want to `.gitignore` `yarn.lock` though, to get the same semantics as before.. (and I'm not yet clear when `yarn` updates that file - if it's only on explicit `add` or `upgrade`, maybe keeping the lock wouldn't be so bad..).

(Using `yarn` with `bower.json` does not work for the ops ui at all (it sorts it (whcih would break `gulp inject` BTW), reads `.bowerrc`, ..and deletes everything under `vendor/assets/bower_components` :)).)

Agreed with `webpack`, even `angular2-cli` is switching from `system,js` to `webpack`, so no question there.. (Investigating `webpack-rails` for the ops ui)

**Comment by chriskacerguis** [comment]
@himdel yeah, going to get @AllenBW and @chalettu to get it done this week (both the npm move and yarn)

**Comment by AllenBW** [comment]
🤘💪👦🍍🐯

**Comment by himdel** [comment]
...as for yarn vs travis .. found https://twitter.com/kentcdodds/status/786282951210262528 .. may help ..
