### ISSUE TITLE
My Services List "created date"

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#309]
The created date is cutoff and I couldn't even tell what it was.  Please move it out of it's own column, and somewhere where it makes sense (and you can read it).

<img width="1258" alt="screen shot 2016-11-02 at 7 51 28 am" src="https://cloud.githubusercontent.com/assets/2414647/19929444/6747ab14-a0d1-11e6-9f45-b3abd84c0eef.png">

**Comment by AparnaKarve** [comment]
@chriskacerguis Unfortunately, we are pretty tight on real estate space here as far as the width of the row goes. 
I really attribute this issue to the PF Listview design. 
Due to the lack of Column headers we have to specify `"Retires"`,` "Created"`, `"Power State"` on each and every row.
Recently there were 2 new additions : `Chargeback` and `Power State` which has exacerbated the PF Listview issue even more.

I've noticed that if you stretch the window out (increase the width basically), you would start seeing some of the cutoff columns properly.

/cc @dclarizio

**Comment by chriskacerguis** [comment]
Hello @AparnaKarve thanks for the feedback.  I think I'll have @chalettu rework that entire layout (also have @serenamarie125 take a look too)

**Comment by chriskacerguis** [comment]
Closing, this is getting reworked in UX

**Comment by chriskacerguis** [comment]
See here: https://www.pivotaltracker.com/story/show/133840391
