### ISSUE TITLE
Move to Jest for for testing

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#964]
Should we use Jest for testing?

https://facebook.github.io/jest/

Thoughts @ohadlevy @martinpovolny @AllenBW @himdel @ManageIQ/core-ui-classic

**Comment by chriskacerguis** [comment]
Thoughts @ohadlevy @martinpovolny @AllenBW @himdel @ManageIQ/core-ui-classic

/cc @ohadlevy

**Comment by AllenBW** [comment]
Looks like it is an assertion library with some stubbing features?  Would replace both chai and sinon... Not opposed to using, aside from dep consolidation, not seeing any *major* benefit (but thats probably also because i haven't used it yet ;-) )

**Comment by vojtechszocs** [comment]
@AllenBW Jest is more than a simple test runner providing assertion and stubbing features, it's a test platform that handles things like ES6 to ES5 transpilation, supports watch mode, has interactive CLI, has built-in snapshot testing support, etc.

> Would replace both chai and sinon

Jest has its own assertion and mocking API. Jest assertions should be close to Chai. As for Sinon you could keep using it with Jest and then gradually migrate to Jest mocking API.

> oh i guess it might also replace mocha AND karma

That's the thing, you probably have webpack + Karma + Mocha + Chai + Sinon. Compare that to Jest which pretty much covers all of that through a single tool / CLI. As for Karma (which you probably run with PhantomJS) I'd avoid launching a dedicated browser instance for the tests, instead I'd use Jest with JSDom env. with Enzyme to unit-test code that relies on DOM env.

**Comment by vojtechszocs** [comment]
Thanks for the thumb ups :smiley: I found this issue while reviewing @ohadlevy's [PR for using Jest in Classic UI](https://github.com/ManageIQ/manageiq-ui-classic/pull/2540).

From what I see, Jest is converging to become something like webpack, but for testing. When building your project, you don't usually run Babel / TypeScript, Sass, UglifyJS etc. separately, but use webpack to manage the whole compilation process. The same thing is with Jest, that's why I see it as a test platform.

I was at [ReactiveConf](https://reactiveconf.com/schedule) last week and got inspired by the "Jest as a Platform" talk, slides are [here](https://github.com/rogeliog/jest-as-a-platform-talk/blob/master/Jest%20as%20a%20Platform.pdf). One of the things mentioned was the possibility to develop custom test runners, see for example [jest-runner-mocha](https://github.com/rogeliog/jest-runner-mocha) - it's experimental, but in future, it should be possible to fully customize the way Jest runs your tests. So if you use Mocha today, and want Jest just for ES6 transpilation and other goodness but still prefer Mocha, you could do that. In future, Jest should allow you to chain test runners, so you could also write your own, e.g. validation test runner which checks if your UI components have tests or are in your Storybook, for example.
